BACKUP DATABASE [PermTest] 
	TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\PermTest.bak' 
	WITH NOFORMAT, NOINIT,  NAME = N'PermTest-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

USE [master]
--BACKUP LOG [PermTest] TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\PermTest_LogBackup_2013-11-12_15-51-01.bak' WITH NOFORMAT, NOINIT,  NAME = N'PermTest_LogBackup_2013-11-12_15-51-01', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
ALTER DATABASE [PermTest] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [PermTest] 
	FROM  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\PermTest.bak' 
	WITH  FILE = 1,  NOUNLOAD,  STATS = 5, REPLACE;
ALTER DATABASE [PermTest] SET MULTI_USER

GO

USE [PermTest]
GO
