USE [master];
GO

if (exists(select * from sys.databases d where d.name = N'TestDb'))
	DROP DATABASE [TestDb];
GO

CREATE DATABASE [TestDb];
GO

USE [TestDb]
GO

if (exists(select * from sys.server_principals p where p.type = N'S' and p.name = 'TestLogin1'))
	DROP LOGIN [TestLogin1];
CREATE LOGIN [TestLogin1] WITH PASSWORD=N'password', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF

if (exists(select * from sys.server_principals p where p.type = N'S' and p.name = 'TestLogin2'))
	DROP LOGIN [TestLogin2];
CREATE LOGIN [TestLogin2] WITH PASSWORD=N'password', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF

if (exists(select * from sys.database_principals p where p.type = N'S' and p.name = 'TestUser1'))
	DROP USER [TestUser1];
CREATE USER [TestUser1] FOR LOGIN [TestLogin1] WITH DEFAULT_SCHEMA=[dbo]

ALTER AUTHORIZATION ON DATABASE::[TestDb] TO [TestLogin2]


GRANT BACKUP DATABASE TO [TestUser1];
GRANT BACKUP LOG TO [TestUser1];
GRANT CREATE DATABASE TO [TestUser1];
GRANT CREATE TYPE TO [TestUser1];
GRANT CREATE ASSEMBLY TO [TestUser1];
GRANT CREATE XML SCHEMA COLLECTION TO [TestUser1];
GRANT CREATE SCHEMA TO [TestUser1];
GRANT CREATE SYNONYM TO [TestUser1];
GRANT CREATE AGGREGATE TO [TestUser1];
GRANT CREATE ROLE TO [TestUser1];
GRANT CREATE MESSAGE TYPE TO [TestUser1];
GRANT CREATE SERVICE TO [TestUser1];
GRANT CREATE CONTRACT TO [TestUser1];
GRANT CREATE REMOTE SERVICE BINDING TO [TestUser1];
GRANT CREATE ROUTE TO [TestUser1];
GRANT CREATE QUEUE TO [TestUser1];
GRANT CREATE SYMMETRIC KEY TO [TestUser1];
GRANT CREATE ASYMMETRIC KEY TO [TestUser1];
GRANT CREATE FULLTEXT CATALOG TO [TestUser1];
GRANT CREATE CERTIFICATE TO [TestUser1];
GRANT CREATE DATABASE DDL EVENT NOTIFICATION TO [TestUser1];
GRANT CONNECT TO [TestUser1];
GRANT CONNECT REPLICATION TO [TestUser1];
GRANT CHECKPOINT TO [TestUser1];
GRANT SUBSCRIBE QUERY NOTIFICATIONS TO [TestUser1];
GRANT AUTHENTICATE TO [TestUser1];
GRANT SHOWPLAN TO [TestUser1];
GRANT ALTER ANY USER TO [TestUser1];
GRANT ALTER ANY ROLE TO [TestUser1];
GRANT ALTER ANY APPLICATION ROLE TO [TestUser1];
GRANT ALTER ANY SCHEMA TO [TestUser1];
GRANT ALTER ANY ASSEMBLY TO [TestUser1];
GRANT ALTER ANY DATASPACE TO [TestUser1];
GRANT ALTER ANY MESSAGE TYPE TO [TestUser1];
GRANT ALTER ANY CONTRACT TO [TestUser1];
GRANT ALTER ANY SERVICE TO [TestUser1];
GRANT ALTER ANY REMOTE SERVICE BINDING TO [TestUser1];
GRANT ALTER ANY ROUTE TO [TestUser1];
GRANT ALTER ANY FULLTEXT CATALOG TO [TestUser1];
GRANT ALTER ANY SYMMETRIC KEY TO [TestUser1];
GRANT ALTER ANY ASYMMETRIC KEY TO [TestUser1];
GRANT ALTER ANY CERTIFICATE TO [TestUser1];
GRANT SELECT TO [TestUser1];
GRANT INSERT TO [TestUser1];
GRANT UPDATE TO [TestUser1];
GRANT DELETE TO [TestUser1];
GRANT REFERENCES TO [TestUser1];
GRANT EXECUTE TO [TestUser1];
GRANT ALTER ANY DATABASE DDL TRIGGER TO [TestUser1];
GRANT ALTER ANY DATABASE EVENT NOTIFICATION TO [TestUser1];
GRANT ALTER ANY DATABASE AUDIT TO [TestUser1];
GRANT VIEW DATABASE STATE TO [TestUser1];
GRANT VIEW DEFINITION TO [TestUser1];
GRANT TAKE OWNERSHIP TO [TestUser1];
GRANT ALTER TO [TestUser1];
GRANT CONTROL TO [TestUser1];


GO
USE [master]
GO

DROP DATABASE [TestDb];
DROP LOGIN [TestLogin1];
DROP LOGIN [TestLogin2];
